data:
  source_url: "https://archive.ics.uci.edu/ml/machine-learning-databases/00352/Online%20Retail.xlsx"
  min_quantity: 0
  drop_na_customer: true
  max_rows: 50000  # ✅ Limite pour limiter la mémoire

rfm:
  snapshot_days: 1
  recency_quantiles: 5
  frequency_quantiles: 5
  monetary_quantiles: 5
  segment_rules:
    champions: [4, 4, 4]
    loyal: [2, 3, 3]

basket_analysis:
  min_support: 0.05      # ✅ 5x plus strict
  min_confidence: 0.3    # ✅ 3x plus strict
  min_lift: 1.2          # ✅ Plus sélectif
  max_rules: 50          # ✅ Limité
  sample_invoices: 1000  # ✅ Échantillon
  sample_products: 500   # ✅ Échantillon

recommendations:
  top_n_segment: 10
  top_n_rules: 5

visualization:
  max_customers_display: 1000
  chart_height: 500